### ISSUE TITLE
xgotext emits backtick-delimited strings into .pot files

### ISSUE THREAD

**Issue by bk2204** [leonelquinteros/gotext#59]
### Is this a bug, an improvement, a proposal or something else? Describe it.

It's a bug that `xgotext` emits backtick-delimited strings into `.pot` files when performing string extraction, because these can't be handled by most gettext-based tools, including gotext itself.

### What's the expected behaviour, the current behaviour and the steps to reproduce it?

Test case:

```
package main

import (
	"fmt"

	"github.com/leonelquinteros/gotext"
)

var Tr = gotext.NewLocale("/usr/share/locale", "en")

func main() {
	fmt.Print(Tr.Get(`This is a multiline string.
It should be formatted properly in a .pot file.`))
}
```

The expected behavior is that `xgotext` emits this as a double-quoted string with `\n` in it.  The current behavior is that it emits it as a backtick-quoted string.

**Comment by chrisd8088** [comment]
Just for my own reference, it appears this issue was actually resolved in PR #82 ... is that correct?

Certainly there are now backtick-delimited [strings](https://github.com/leonelquinteros/gotext/blob/2a3f89acc7e6f9104830a056a5bdc0f10823aabf/cli/xgotext/fixtures/main.go#L59-L66) in the test fixtures which are correctly output by recent versions of `xgotext` as double-quoted strings with newlines.

Running `xgotext -in . -out pot` in a directory with a `main.go` from the test case above, plus valid `go.mod` and `go.sum` files, generates a `pot/default.pot` file which contains:

```
#: main.go:12
msgid "This is a multiline string.\nIt should be formatted properly in a .pot file."
msgstr ""
```

So it definitely looks resolved to me now.  Thanks to @didrocks for the fix!
